-- Generated admin_users INSERT from CSV
-- Source: c:\\Users\\Admin\\WDP\\All - Admin Users.csv
-- Generated: 2025-11-01 09:50:01
-- Default password is bcrypt hash for 'password'

INSERT INTO admin_users (user_id, username, password, email, role, first_name, surname, is_active, department, sub_department) VALUES
(2204, 'Cynthia', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Cynthia', 'Dzilla', 1, 'Executive', 'Office of the Governor'),
(2163, 'Kinana', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Kinana', 'Juma', 1, 'Executive', 'Office of the Governor'),
(2730, 'Florence', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Florence', 'Mwilole', 1, 'Executive', 'Office of the Governor'),
(1090, 'Joab', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Joab', 'Unda', 1, 'Executive', 'Office of the County Secretary'),
(4148, 'Hussein', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Hussein', 'S.', 1, 'Executive', 'Office of the County Secretary'),
(4760, 'James', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'James', 'Mwanza', 1, 'Executive', 'Office of the County Attorney'),
(2012, 'Joseph', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Joseph', 'Atunda', 1, 'Executive', 'Office of the County Attorney'),
(3150, 'Leah', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Leah', 'Akinyi', 1, 'Finance, Economic Planning & Digital Transformation', 'Finance & Investment'),
(2162, 'Kaltuma', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Kaltuma', 'Ahmed', 1, 'Finance, Economic Planning & Digital Transformation', 'Finance & Investment'),
(2236, 'Omar', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Omar', 'Mahmoud', 1, 'Finance, Economic Planning & Digital Transformation', 'Finance & Investment'),
(3936, 'Fauzia', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Fauzia', 'Mohamed', 1, 'Finance, Economic Planning & Digital Transformation', 'Finance & Investment'),
(4766, 'Abdirazak', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Abdirazak', 'Abdikadir', 1, 'Finance, Economic Planning & Digital Transformation', 'Economic Planning & Digital Transformation'),
(4846, 'Halima', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Halima', 'Hussein', 1, 'Finance, Economic Planning & Digital Transformation', 'Economic Planning & Digital Transformation'),
(4759, 'Adhan', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Adhan', 'Kuso', 1, 'Finance, Economic Planning & Digital Transformation', 'Economic Planning & Digital Transformation'),
(4406, 'Everlyne', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Everlyne', 'Owour', 1, 'Cooperatives', 'Mombasa Water Supply & Sanitation Company Limited (MOWASSCO)'),
(6010, 'Laban', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Laban', 'Ainga', 1, 'Cooperatives', 'Mombasa Water Supply & Sanitation Company Limited (MOWASSCO)'),
(6246, 'Edwin', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Edwin', 'Mwale', 1, 'Cooperatives', 'Mombasa Water Supply & Sanitation Company Limited (MOWASSCO)'),
(4774, 'Angela', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Angela', 'Oseko', 1, 'Cooperatives', 'Mombasa Investment Corporation (MIC)'),
(1826, 'Athman', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Athman', 'Matano', 1, 'Department of Public Service Administration, Youth, Gender and Sports', 'Public Service Administration'),
(2906, 'Maryam', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Maryam', 'Abdillahi', 1, 'Department of Public Service Administration, Youth, Gender and Sports', 'Public Service Administration'),
(4980, 'Diana', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Diana', 'Gabriel', 1, 'Department of Public Service Administration, Youth, Gender and Sports', 'Public Service Administration'),
(2201, 'Sophie', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Sophie', 'Ismail', 1, 'Department of Health', 'Public Health & Disease Prevention'),
(246, 'Lucy', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Lucy', 'Nyambura', 1, 'Department of Health', 'Public Health & Disease Prevention'),
(3164, 'Sumeiya', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Sumeiya', 'Hussein', 1, 'Department of Health', 'Public Health & Disease Prevention'),
(2263, 'Suleiman', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Suleiman', 'Mohammed', 1, 'Department of Health', 'Clinical Services'),
(58, 'Esha', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Esha', 'Swaleh', 1, 'Department of Health', 'Clinical Services'),
(4841, 'Ibrahim', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Ibrahim', 'Farhad', 1, 'Department of Health', 'Clinical Services'),
(492, 'Lilian', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Lilian', 'Wachuka', 1, 'Department of Health', 'Coast General Teaching And Referral Hospital (CGTRH)'),
(2628, 'Daniel', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Daniel', 'Chai', 1, 'Department of Health', 'Coast General Teaching And Referral Hospital (CGTRH)'),
(5071, 'Jessica', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Jessica', 'Judith', 1, 'Department of Health', 'Coast General Teaching And Referral Hospital (CGTRH)'),
(6428, 'Yahya', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Yahya', 'Abeid', 1, 'Department of Health', 'Coast General Teaching And Referral Hospital (CGTRH)'),
(6338, 'Mohamed', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Mohamed', 'Shuaib', 1, 'Department of Health', 'Coast General Teaching And Referral Hospital (CGTRH)'),
(474, 'Nancy', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Nancy', 'Wairimu', 1, 'Department of Health', 'Clinical Services'),
(685, 'Roselyne', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Roselyne', 'Wangari', 1, 'Department of Health', 'Clinical Services'),
(463, 'Cecilia', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Cecilia', 'Kajumwa', 1, 'Department of Health', 'Clinical Services'),
(3479, 'Ifdhel', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Ifdhel', 'Badi', 1, 'Department of Health', 'Clinical Services'),
(684, 'Phelisters', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Phelisters', 'Ngare', 1, 'Department of Health', 'Clinical Services'),
(5724, 'Saadia', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Saadia', 'Abdi', 1, 'Department of Health', 'Clinical Services'),
(5739, 'Ali', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Ali', 'Abdusalam', 1, 'Department of Health', 'Clinical Services'),
(5198, 'AthmanR.', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Athman', 'Rajab', 1, 'Department of Health', 'Clinical Services'),
(5752, 'Salma', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Salma', 'Ali', 1, 'Department of Health', 'Clinical Services'),
(5717, 'Amina', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Amina', 'Ali', 1, 'Department of Health', 'Clinical Services'),
(5055, 'Henrita', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Henrita', 'Shali', 1, 'Department of Health', 'Clinical Services'),
(3492, 'Barrau', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Barrau', 'M', 1, 'Department of Health', 'Clinical Services'),
(3832, 'Raymond', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Raymond', 'N.', 1, 'Department of Public Service Administration, Youth, Gender and Sports', 'Youth, Gender, Sports & Social Services'),
(4094, 'Fatma', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Fatma', 'S.', 1, 'Department of Public Service Administration, Youth, Gender and Sports', 'Youth, Gender, Sports & Social Services'),
(2978, 'Julie', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Julie', 'Omondi', 1, 'Department of Public Service Administration, Youth, Gender and Sports', 'Youth, Gender, Sports & Social Services'),
(3932, 'Ambrose', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Ambrose', 'Kelle', 1, 'Department of Transport, Infrastructure & Governance', 'Governance'),
(5040, 'Hannan', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Hannan', 'Abdun', 1, 'Department of Transport, Infrastructure & Governance', 'Governance'),
(3790, 'Brian', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Brian', 'Email', 1, 'Department of Transport, Infrastructure & Governance', 'Governance'),
(1670, 'Kennedy', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Kennedy', 'Asati', 1, 'Department of Transport, Infrastructure & Governance', 'Transport & Infrastructure'),
(2943, 'Ruth', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Ruth', 'Akeyo', 1, 'Department of Transport, Infrastructure & Governance', 'Transport & Infrastructure'),
(5115, 'Maimuna', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Maimuna', 'Abdi', 1, 'Department of Transport, Infrastructure & Governance', 'Transport & Infrastructure'),
(1306, 'Hashora', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Hashora', 'Morowa', 1, 'Department of Lands, Urban Planning and Housing', 'Lands, Urban Planning and Housing'),
(1095, 'Bakari', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Bakari', 'Hamisi', 1, 'Department of Lands, Urban Planning and Housing', 'Lands, Urban Planning and Housing'),
(1279, 'Neema', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Neema', 'Mwidani', 1, 'Department of Lands, Urban Planning and Housing', 'Lands, Urban Planning and Housing'),
(2562, 'Ahmed', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Ahmed', 'Al-Amin', 1, 'Department of Lands, Urban Planning and Housing', 'Serikali Mitaani'),
(4703, 'AbdulRahman', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'AbdulRahman', 'Kassim', 1, 'Department of Lands, Urban Planning and Housing', 'Serikali Mitaani'),
(4346, 'Abdillatif', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Abdillatif', 'Abdisalan', 1, 'Department of Lands, Urban Planning and Housing', 'Serikali Mitaani'),
(2288, 'Harun', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Harun', 'Iddi', 1, 'Department of Education & Vocational Training', 'Department of Education & Vocational Training'),
(2629, 'AminaS.', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Amina', 'Shee', 1, 'Department of Education & Vocational Training', 'Department of Education & Vocational Training'),
(2015, 'FlorenceK.', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Florence', 'Kache', 1, 'Department of Education & Vocational Training', 'Department of Education & Vocational Training'),
(2868, 'Nasra', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Nasra', 'Mohamed', 1, 'Department of  Trade, Tourism and Culture', 'Department of  Trade, Tourism and Culture'),
(2254, 'Amal', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Amal', 'Mohamed', 1, 'Department of  Trade, Tourism and Culture', 'Department of  Trade, Tourism and Culture'),
(4909, 'Alexander', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Alexander', 'Kangentu', 1, 'Department of  Trade, Tourism and Culture', 'Department of  Trade, Tourism and Culture'),
(4240, 'Salwa', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Salwa', 'Said', 1, 'Department of Climate Change, Energy and Natural Resources', 'Department of Climate Change, Energy and Natural Resources'),
(2303, 'AminaW.', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Amina', 'Walegwa', 1, 'Department of Climate Change, Energy and Natural Resources', 'Department of Climate Change, Energy and Natural Resources'),
(4190, 'Mohammed', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Mohammed', 'Mwachiro', 1, 'Department of Climate Change, Energy and Natural Resources', 'Department of Climate Change, Energy and Natural Resources'),
(4763, 'Habon', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Habon', 'Mohamed', 1, 'Department of Environment and Water', 'Environment and Solid Waste Management'),
(4473, 'Kevin', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Kevin', 'Ouma', 1, 'Department of Environment and Water', 'Environment and Solid Waste Management'),
(4199, 'Aisha', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Aisha', 'Mohamed', 1, 'Department of Environment and Water', 'Environment and Solid Waste Management'),
(4683, 'John', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'John', 'Xavier', 1, 'Department of Environment and Water', 'Water and Sanitation'),
(1327, 'Nixon', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Nixon', 'Kilukumi', 1, 'Department of Environment and Water', 'Water and Sanitation'),
(4507, 'Bramwel', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Bramwel', 'Wanami', 1, 'Department of Environment and Water', 'Water and Sanitation'),
(532, 'Abigael', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Abigael', 'Andanje', 1, 'Department of Blue Economy, Cooperatives, Agriculture and Livestock', 'Department of Blue Economy, Cooperatives, Agriculture and Livestock'),
(4502, 'Lydia', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Lydia', 'Michira', 1, 'Department of Blue Economy, Cooperatives, Agriculture and Livestock', 'Department of Blue Economy, Cooperatives, Agriculture and Livestock'),
(2675, 'Takash', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Takash', 'Mahfudh', 1, 'Department of Blue Economy, Cooperatives, Agriculture and Livestock', 'Department of Blue Economy, Cooperatives, Agriculture and Livestock'),
(1667, 'Sheba', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Sheba', 'Fakih', 1, 'Mombasa County Public Service Board', 'Mombasa County Public Service Board'),
(2695, 'Andrew', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Andrew', 'Muasya', 1, 'Mombasa County Public Service Board', 'Mombasa County Public Service Board'),
(2846, 'Joan', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'hr_admin', 'Joan', 'Phidiliah', 1, 'Mombasa County Public Service Board', 'Mombasa County Public Service Board'),
(3163, 'Swaleh', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'it_admin', 'Swaleh', 'Bakari', 1, NULL, 'N/A'),
(5901, 'Saleh', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'it_admin', 'Saleh', 'Ali', 1, NULL, 'N/A'),
(5896, 'Mariam', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'it_admin', 'Mariam', 'Jamal', 1, NULL, 'N/A'),
(4878, 'Samuel', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'it_admin', 'Samuel', 'Mwanjala', 1, NULL, 'N/A'),
(1143, 'Abushiri', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'it_admin', 'Ahmed', 'Abushiri', 1, NULL, 'N/A'),
(4187, 'JamesT.', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'it_admin', 'James', 'Tayo', 1, NULL, 'N/A'),
(2500, 'Anastansia', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, 'super_admin', 'Anastansia', 'Nabukenya', 1, NULL, 'N/A');
